In [2]:
import torch
from torch import nn

#input data
X = torch.tensor([
    [10],
    [37.78]
], dtype=torch.float32)

# valid results
y = torch.tensor([
    [50],
    [100]
], dtype=torch.float32)

model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

for i in range(0, 100000):
  optimizer.zero_grad()
  outputs = model(X)
  loss = loss_fn(outputs, y)
  loss.backward()
  optimizer.step()

  if i % 1000 == 0:
    print(model.bias)
    print(model.weight)


print("-------------------")

measurements = torch.tensor([
    [37.5]
], dtype=torch.float32)

model.eval()
with torch.no_grad():
  prediction = model(measurements)
  print(prediction)

Parameter containing:
tensor([-0.5340], requires_grad=True)
Parameter containing:
tensor([[1.1512]], requires_grad=True)
Parameter containing:
tensor([1.1172], requires_grad=True)
Parameter containing:
tensor([[2.7663]], requires_grad=True)
Parameter containing:
tensor([2.6375], requires_grad=True)
Parameter containing:
tensor([[2.7188]], requires_grad=True)
Parameter containing:
tensor([4.0830], requires_grad=True)
Parameter containing:
tensor([[2.6735]], requires_grad=True)
Parameter containing:
tensor([5.4573], requires_grad=True)
Parameter containing:
tensor([[2.6305]], requires_grad=True)
Parameter containing:
tensor([6.7640], requires_grad=True)
Parameter containing:
tensor([[2.5896]], requires_grad=True)
Parameter containing:
tensor([8.0064], requires_grad=True)
Parameter containing:
tensor([[2.5508]], requires_grad=True)
Parameter containing:
tensor([9.1876], requires_grad=True)
Parameter containing:
tensor([[2.5138]], requires_grad=True)
Parameter containing:
tensor([10.3106],