# **Conceptos Basicos**

##Emulando una neurona:

In [1]:
b = 32    #simulando el bias
w1 = 1.8  #simulando el weight

X1 = 10 #valor en centigrados

y_pred = 1 * b + X1 * w1

print(y_pred) #prediccion en farenheit

50.0


Que es un tensor ?

In [2]:
import torch

0-tensor:

In [3]:
b = torch.tensor(32)
w1 = torch.tensor(1.8)

X1 = torch.tensor(10)

y_pred = 1 * b + X1 * w1

print(type(y_pred))
print(y_pred)

<class 'torch.Tensor'>
tensor(50.)


In [4]:
b = torch.tensor(32)
w1 = torch.tensor(1.8)

X1 = torch.tensor([10, 38, 100, 150])

y_pred = 1 * b + X1 * w1

print(type(y_pred))
print(y_pred)


<class 'torch.Tensor'>
tensor([ 50.0000, 100.4000, 212.0000, 302.0000])


In [5]:
print(b.shape)
print(X1.shape)
print(b.size())
print(X1.size())

print(type(y_pred))
print(y_pred)
print(y_pred[0])
print(y_pred[0].item())

torch.Size([])
torch.Size([4])
torch.Size([])
torch.Size([4])
<class 'torch.Tensor'>
tensor([ 50.0000, 100.4000, 212.0000, 302.0000])
tensor(50.)
50.0


Tensor Matrix

In [6]:
X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
])

print(X)
print(X.size())

print("Matrix de:")
print(f'Numero de filas: {X.size(0)}') #Numero de filas
print(f'Numero de columnas: {X.size(1)}') #Numero de columnas


tensor([[ 10],
        [ 38],
        [100],
        [150]])
torch.Size([4, 1])
Matrix de:
Numero de filas: 4
Numero de columnas: 1


In [7]:
print(X[2,0]) # trae el tercer valor de la primera columna

tensor(100)


In [ ]:
print(X[2, :])

tensor([100])


##Creando un modelo con parametros estaticos

In [9]:
from torch import nn


In [10]:
X = torch.tensor([
    [10.0],
    [38.0],
    [100.0],
    [150.0]
])

model = nn.Linear(1,1) # one input and one output
print(model)
print(model.bias)   #inicializado con numero random
print(model.weight) #inicializado con numero random


Linear(in_features=1, out_features=1, bias=True)
Parameter containing:
tensor([-0.8425], requires_grad=True)
Parameter containing:
tensor([[0.4295]], requires_grad=True)


In [11]:
y_pred = model(X)
print(y_pred)

tensor([[ 3.4522],
        [15.4772],
        [42.1041],
        [63.5774]], grad_fn=<AddmmBackward0>)


Ajustar el **BIAS**
Cerca de los valores pero todavia falta el *weight*

In [12]:
model.bias = nn.Parameter(
    torch.tensor([32.0])
)
y_pred = model(X)
print(y_pred)

tensor([[36.2947],
        [48.3197],
        [74.9466],
        [96.4199]], grad_fn=<AddmmBackward0>)


AJUSTAR el **WEIGHT**
Llegamos a la misma prediccion pero sin hacer uso de la formula:

In [13]:
model.weight = nn.Parameter(
    torch.tensor([[1.8]]) # Notice: X matrix has one row and one column
)
y_pred = model(X)
print(y_pred)

tensor([[ 50.0000],
        [100.4000],
        [212.0000],
        [302.0000]], grad_fn=<AddmmBackward0>)


Trabajando con los data types dentro de los tensors:

In [ ]:
a_int = 5
b_float = 5.5
print(a_int)
print(type(a_int))
print(b_float)
print(type(b_float))
print(X.dtype)

5
<class 'int'>
5.5
<class 'float'>
torch.float32


In [ ]:
X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
])

print(X.dtype)

result = X * 0.5

print(result)

print(result.dtype)

torch.int64
tensor([[ 5.],
        [19.],
        [50.],
        [75.]])
torch.float32


In [ ]:
print(X.dtype)

X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
], dtype=torch.float32)

print(X.dtype)

torch.int64
torch.float32


In [ ]:
X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
])

model = nn.Linear(1,1)

model.bias = nn.Parameter(
    torch.tensor([32])
)
model.weight = nn.Parameter(
    torch.tensor([[1.8]])
)

print(model.bias)
print(model.weight)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [ ]:
X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
])

model = nn.Linear(1,1)

model.bias = nn.Parameter(
    torch.tensor([32], dtype=torch.float32)
)
model.weight = nn.Parameter(
    torch.tensor([[1.8]])
)

print(model.bias)
print(model.weight)

ypred = model(X)
print(y_pred)

Parameter containing:
tensor([32.], requires_grad=True)
Parameter containing:
tensor([[1.8000]], requires_grad=True)


RuntimeError: mat1 and mat2 must have the same dtype, but got Long and Float

In [ ]:
X = torch.tensor([
    [10],
    [38],
    [100],
    [150]
], dtype=torch.float32)

model = nn.Linear(1,1)

model.bias = nn.Parameter(
    torch.tensor([32], dtype=torch.float32)
)
model.weight = nn.Parameter(
    torch.tensor([[1.8]], dtype=torch.float32)
)

print(model.bias)
print(model.weight)

ypred = model(X)
print(y_pred)

Parameter containing:
tensor([32.], requires_grad=True)
Parameter containing:
tensor([[1.8000]], requires_grad=True)
tensor([[ 50.0000],
        [100.4000],
        [212.0000],
        [302.0000]], grad_fn=<AddmmBackward0>)
