# Entranando una neurona

##Entrenamiento de una neurona basado en datos estaticos

In [ ]:
import torch
from torch import nn

In [ ]:
# Primer set de datos
# El equivalente de 10 grados centigrados es 50 grados farenheith
X1 = torch.tensor([[10]], dtype=torch.float32)
y1 = torch.tensor([[50]], dtype=torch.float32)

# Segundo set de datos
# El equivalente de 37.78 grados centigrados es 100 grados farenheith
X2 = torch.tensor([[37.78]], dtype=torch.float32)
y2 = torch.tensor([[100]], dtype=torch.float32)


In [ ]:
# Definimos una neurona con:
# Funcion de perdida MSE
# Optimizador SGD

model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

In [ ]:
#Comenzamos el aprendizaje:
optimizer.zero_grad()

print(f'Weight antes del aprendizaje: {model.weight}')
print(f'Bias antes del aprendizaje: {model.bias}')


outputs = model(X1)
loss = loss_fn(outputs, y1)
loss.backward()
optimizer.step()

print(f'Weight despues del aprendizaje: {model.weight}')
print(f'Bias antes del aprendizaje: {model.bias}')


y1_pred = model(X1)
print("y1_pred = ", y1_pred)

Weight antes del aprendizaje: Parameter containing:
tensor([[1.2427]], requires_grad=True)
Bias antes del aprendizaje: Parameter containing:
tensor([-0.9008], requires_grad=True)
Weight despues del aprendizaje: Parameter containing:
tensor([[2.0122]], requires_grad=True)
Bias antes del aprendizaje: Parameter containing:
tensor([-0.8239], requires_grad=True)
y1_pred =  tensor([[19.2982]], grad_fn=<AddmmBackward0>)


In [ ]:
for i in range(0, 1000):
  optimizer.zero_grad()
  outputs = model(X1)
  loss = loss_fn(outputs, y1)
  loss.backward()
  optimizer.step()

  optimizer.zero_grad()
  outputs = model(X2)
  loss = loss_fn(outputs, y2)
  loss.backward()
  optimizer.step()


y1_pred = model(X1)
print("y1_pred = ", y1_pred)
# learning rate too large (NAN error)

y1_pred =  tensor([[nan]], grad_fn=<AddmmBackward0>)


In [ ]:
model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

for i in range(0, 100000):
  optimizer.zero_grad()
  outputs = model(X1)
  loss = loss_fn(outputs, y1)
  loss.backward()
  optimizer.step()

  optimizer.zero_grad()
  outputs = model(X2)
  loss = loss_fn(outputs, y2)
  loss.backward()
  optimizer.step()

  if i % 1000 == 0:
    print(model.bias)
    print(model.weight)


y1_pred = model(X1)
print("y1_pred = ", y1_pred)

y2_pred = model(X2)
print("y2_pred = ", y2_pred)

Parameter containing:
tensor([-0.0386], requires_grad=True)
Parameter containing:
tensor([[0.2902]], requires_grad=True)
Parameter containing:
tensor([3.1641], requires_grad=True)
Parameter containing:
tensor([[2.6644]], requires_grad=True)
Parameter containing:
tensor([5.9838], requires_grad=True)
Parameter containing:
tensor([[2.5799]], requires_grad=True)
Parameter containing:
tensor([8.5277], requires_grad=True)
Parameter containing:
tensor([[2.5036]], requires_grad=True)
Parameter containing:
tensor([10.8229], requires_grad=True)
Parameter containing:
tensor([[2.4348]], requires_grad=True)
Parameter containing:
tensor([12.8937], requires_grad=True)
Parameter containing:
tensor([[2.3727]], requires_grad=True)
Parameter containing:
tensor([14.7620], requires_grad=True)
Parameter containing:
tensor([[2.3167]], requires_grad=True)
Parameter containing:
tensor([16.4477], requires_grad=True)
Parameter containing:
tensor([[2.2662]], requires_grad=True)
Parameter containing:
tensor([17.96